name: Extract Artception Data

on:
  workflow_dispatch:
    inputs:
      category:
        description: "Catégorie à extraire"
        required: true
        type: choice
        options: [graphisme, architecture, musique, cinema, photo, mode, design, peinture, cuisine, all]
      lang:
        description: "Langues préférées (labels WDQS). Ex: fr,en"
        required: false
        default: "fr,en"
      limit:
        description: "Limite d'items (tests)"
        required: false
        default: "200"
      mode:
        description: "Écriture de core/styles.csv (isoler la catégorie ou fusionner)"
        required: true
        type: choice
        options: [isolate, merge]
        default: isolate
      wipe_out:
        description: "Nettoyer out/csv/ avant extraction"
        required: true
        type: boolean
        default: true

  schedule:
    - cron: "0 3 * * 1"   # hebdo

permissions:
  contents: write   # nécessaire pour pousser sur la branche 'data'

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Clean previous outputs
        if: ${{ inputs.wipe_out == 'true' }}
        run: rm -rf out/csv || true

      - name: Run extractor
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          python -m scripts.extract \
            --category "${{ inputs.category }}" \
            --lang "${{ inputs.lang }}" \
            --limit "${{ inputs.limit }}" \
            --mode "${{ inputs.mode }}"

      - name: Upload CSV artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-${{ inputs.category }}
          path: out/csv/

      - name: Commit data branch
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B data
          mkdir -p data_drop
          if [ -d "out/csv" ]; then cp -r out/csv/* data_drop/ || true; fi
          git add data_drop || true
          git commit -m "data: update ${{ inputs.category }}" || true
          git push -f origin data
