name: Extract Artception Data

on:
  workflow_dispatch:
    inputs:
      category:
        type: choice
        options: [graphisme, architecture, musique, cinema, photo, mode, design, peinture, cuisine, all]
      lang:
        default: "fr,en"
      limit:
        default: "200"
      mode:
        description: "Ecriture du core/styles.csv"
        type: choice
        options: [isolate, merge]
        default: isolate
      wipe_out:
        description: "Nettoyer out/csv/ avant extraction"
        type: boolean
        default: true
jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Clean previous outputs
        if: ${{ inputs.wipe_out == 'true' }}
        run: rm -rf out/csv || true
      - name: Run extractor
        env: { TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }} }
        run: |
          python -m scripts.extract \
            --category "${{ inputs.category }}" \
            --lang "${{ inputs.lang }}" \
            --limit "${{ inputs.limit }}" \
            --mode "${{ inputs.mode }}"
      - uses: actions/upload-artifact@v4
        if: always()
        with: { name: csv-${{ inputs.category }}, path: out/csv/ }
      - name: Commit data branch
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B data
          mkdir -p data_drop
          if [ -d "out/csv" ]; then cp -r out/csv/* data_drop/ || true; fi
          git add data_drop || true
          git commit -m "data: update ${{ inputs.category }}" || true
          git push -f origin data
